### ISSUE TITLE
Show progress percentage

### ISSUE THREAD

**Issue by evillt** [evillt/loading-screen#3]
[<img alt="Issuehunt badges" src="https://img.shields.io/badge/IssueHunt-%2440%20Rewarded-%237E24E3.svg" />](https://issuehunt.io/r/evillt/loading-screen/issues/3)

This is a configurable option

```js
new LoadingScreenPlugin({
  showPercent: true
})
```

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $40.00)

- [<img src='https://avatars3.githubusercontent.com/u/44827199?v=4' alt='issuehunt' width=24 height=24> issuehunt](https://issuehunt.io/u/issuehunt) ($40.00)
### Submitted pull Requests
- [#6 feat: support show percent while loading app](https://issuehunt.io/r/evillt/loading-screen/pull/6)
---

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/evillt/loading-screen/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
---
IssueHunt has been backed by the following sponsors. [Become a sponsor](https://issuehunt.io/membership/members)
</details>

**Comment by masquel** [comment]
I'll try this, @evillt can you provide more info?
